# frozen_string_literal: true

source "https://rubygems.org"

gem "brute"
gem "brute_rack"
gem "falcon"
gem "async-service"

# Local development:
# gem "brute",      path: "../../../brute"
# gem "brute_rack", path: "../.."
